### ISSUE TITLE
Yumisign breaks Nextcloud Upgrade 29.0.10

### ISSUE THREAD

**Issue by Githopp192** [rcdevs/yumisign_nextcloud#1]
Error: Class "OCA\RCDevs\Service\ConfigurationService" not found in /var/www/html/nextcloud/apps/yumisign_nextcloud/lib/Service/ConfigurationService.php:30  
Stack trace:  
#0 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(576): include()  
#1 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}()  
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()  
#3 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct()  
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()  
#5 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(471): OC\AppFramework\Utility\SimpleContainer->query()  
#6 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(443): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()  
#7 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\DependencyInjection\DIContainer->query()  
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()  
#9 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): array_map()  
#10 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass()  
#11 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()  
#12 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(471): OC\AppFramework\Utility\SimpleContainer->query()  
#13 /var/www/html/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()  
#14 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query()  
#15 /var/www/html/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get()  
#16 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(486): OCP\Server::get()  
#17 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(510): OC\DB\MigrationService->createInstance()  
#18 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(409): OC\DB\MigrationService->executeStep()  
#19 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(777): OC\DB\MigrationService->migrate()  
#20 /var/www/html/nextcloud/lib/private/Installer.php(184): OC_App::updateApp()  
#21 /var/www/html/nextcloud/lib/private/Updater.php(417): OC\Installer->updateAppstoreApp()  
#22 /var/www/html/nextcloud/lib/private/Updater.php(275): OC\Updater->upgradeAppStoreApps()  
#23 /var/www/html/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()  
#24 /var/www/html/nextcloud/core/Command/Upgrade.php(216): OC\Updater->upgrade()  
#25 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute()  
#26 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()  
#27 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()  
#28 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()  
#29 /var/www/html/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()  
#30 /var/www/html/nextcloud/console.php(102): OC\Console\Application->run()  
#31 /var/www/html/nextcloud/occ(11): require_once('...')  
#32 {main}

**Comment by ericjamesbye7** [comment]
Hello
We had the same issue on the 30's and I fixed it in the new release.
Just to be sure another file is not missing, would you mind if you gave me your YumiSign installed version, the current Nextcloud version (before trying to upgrade).
And the database system you use with your Nextcloud server.
Regards
EJB

**Comment by Githopp192** [comment]
Hello EJB, before the upgrade the Yumisign version was: - yumisign_nextcloud: 1.29.2

and ==>

Nextcloud version:29.0.9.2
Red Hat Enterprise Linux release 8.10 (Ootpa) 10.6.20-MariaDB,
Apache/2.4.37
PHP 8.3.13

Best
Mike

**Comment by ericjamesbye7** [comment]
The YMS modules has to be upgraded to version 1.29.5
We tested and published it yesterday
Keep me posted about this upgrade.
Regards
EJB

**Comment by Githopp192** [comment]
yes, i do and thanks .. (have got some automatic update script in place, which updates new apps after a wait time of six days :-) 
Best 
Mike

**Comment by ericjamesbye7** [comment]
So does the issue fixed for your server ?

**Comment by Githopp192** [comment]
i just did the manual upgrade to 1.29.6 - then enabled the app again.

So, it seems to work .. in the log i see this last message: 

{"reqId":"xxxxI","level":3,"time":"2024-12-12T11:03:03+01:00","remoteAddr":"xxxxx","user":"xxxx","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/yumisign_nextcloud/api/v1/settings/check","message":"ConnectionErrorException [cURL returned unwanted code (401). This process is skipped for function checkServerUrl/OCA\\RCDevs\\Service\\SettingsService//var/www/html/nextcloud/apps/yumisign_nextcloud/rcdevsBundle/Service/SettingsService.php:84.]","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0","version":"29.0.10.1","data":[]}

**Comment by ericjamesbye7** [comment]
I'm going to watch this point.
But 401 clearly means the API key does not match with YMS server.
Regards
EJB

**Comment by Githopp192** [comment]
Thx EJB .. i think it should work now, thank you

**Comment by ericjamesbye7** [comment]
Ok, I close the issue.
Feel free to contact me if needed
Have a good day
Regards
EJB
